version: "3"
services:
  deeplinking:
    container_name: deepLink_app
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    links: 
      - mysqldb:mysqldb
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./db/CreateTable.sql:/docker-entrypoint-initdb.d/CreateTable.sql
      - db_volume:/var/lib/mysql
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"
volumes:
  db_volume:
